# Generated by Django 4.2.13 on 2024-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='price',
            new_name='ticket_price',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Where will the event take place'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Single Event', 'Single Event'), ('Recurring Event', 'Recurring Event')], max_length=255, verbose_name='Event Type'),
        ),
    ]
