# Generated by Django 4.2.13 on 2024-07-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_price_event_ticket_price_event_ticket_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='Category/%y/%m/%d/'),
        ),
    ]
