# Generated by Django 4.2.13 on 2024-09-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_attendee_alter_category_image_alter_event_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_price',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='event.event'),
        ),
    ]
